groups:
  - name: disk-usage
    rules:
      - alert: DiskSpaceLow
        expr: |
          (node_filesystem_size_bytes{fstype!="tmpfs", fstype!="overlay"} - node_filesystem_free_bytes{fstype!="tmpfs", fstype!="overlay"})
          / node_filesystem_size_bytes{fstype!="tmpfs", fstype!="overlay"} * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "ðŸ§¨ Disque presque plein : {{ $labels.device }} sur {{ $labels.mountpoint }}"
          description: "Le disque {{ $labels.device }} montÃ© sur {{ $labels.mountpoint }} est utilisÃ© Ã  plus de 80â€¯%."

